"""Phase 3 MCP Protocol Test: LangChain Integration & Dynamic Tool Discovery.

Demonstrates and verifies:
1. How LangChain connects to the MCP server via `mcp_session_scope`.
2. How the MCP client discovers tools dynamically using `load_mcp_tools`.
3. How MCP tool schemas are converted into LangChain `BaseTool` objects.
4. Executing LangChain `BaseTool` instances via `tool.ainvoke(...)`.
5. How LangChain models bind these tools via `bind_tools` / OpenAI function calling schema.
"""

import asyncio
import json
import os
import sys
import pytest

# Ensure workspace root is in sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from langchain_core.utils.function_calling import convert_to_openai_tool
from backend.mcp_client import mcp_session_scope


async def run_phase3_langchain_verification():
    print("=" * 60)
    print("  PHASE 3: LANGCHAIN MCP INTEGRATION & TOOL DISCOVERY")
    print("=" * 60)

    # 1. Connect to MCP Server and discover tools as LangChain BaseTool instances
    async with mcp_session_scope() as (session, tools):
        print(f"\n[1] Dynamic Discovery:")
        print(f"    Loaded {len(tools)} LangChain BaseTool instances from MCP Server:")

        tools_by_name = {t.name: t for t in tools}
        for name, tool in tools_by_name.items():
            print(f"\n    Tool: {name}")
            print(f"      Description: {tool.description.strip().splitlines()[0]}")
            print(f"      Arguments:   {json.dumps(tool.args)}")

        # Verify all 3 tools exist
        assert "get_repository" in tools_by_name
        assert "get_repository_tree" in tools_by_name
        assert "read_file" in tools_by_name

        # 2. Inspect the OpenAI-compatible function calling schemas generated by LangChain
        print("\n[2] LLM Tool Calling Schemas (Generated for OpenAI/Gemini/Groq/Anthropic):")
        for tool in tools:
            schema = convert_to_openai_tool(tool)
            func_def = schema["function"]
            print(f"    - Function: {func_def['name']}")
            print(f"      Parameters: {list(func_def['parameters']['properties'].keys())}")
            print(f"      Required:   {func_def['parameters'].get('required', [])}")

        # 3. Invoke get_repository via LangChain BaseTool interface
        print("\n[3] Calling get_repository via tool.ainvoke():")
        repo_tool = tools_by_name["get_repository"]
        repo_res = await repo_tool.ainvoke({"repo_url": "octocat/Hello-World"})
        print(f"    Response type: {type(repo_res)}")

        # Parse text content from response
        res_text = repo_res[0]["text"] if isinstance(repo_res, list) else str(repo_res)
        repo_data = json.loads(res_text)
        print(f"    Repo Name:  {repo_data.get('name')}")
        print(f"    Stars:      {repo_data.get('stars')}")
        assert repo_data.get("name") == "Hello-World"
        assert repo_data.get("error") is False

        # 4. Invoke get_repository_tree via LangChain BaseTool interface
        print("\n[4] Calling get_repository_tree via tool.ainvoke():")
        tree_tool = tools_by_name["get_repository_tree"]
        tree_res = await tree_tool.ainvoke({"repo_url": "octocat/Hello-World"})
        tree_text = tree_res[0]["text"] if isinstance(tree_res, list) else str(tree_res)
        tree_data = json.loads(tree_text)
        print(f"    Branch:         {tree_data.get('branch')}")
        print(f"    Filtered Files: {tree_data.get('filtered_files_count')}")
        assert tree_data.get("error") is False
        assert len(tree_data.get("files", [])) >= 1

        # 5. Invoke read_file via LangChain BaseTool interface
        print("\n[5] Calling read_file via tool.ainvoke():")
        read_tool = tools_by_name["read_file"]
        file_res = await read_tool.ainvoke({
            "repo_url": "octocat/Hello-World",
            "file_path": "README",
        })
        file_text = file_res[0]["text"] if isinstance(file_res, list) else str(file_res)
        file_data = json.loads(file_text)
        print(f"    File:    {file_data.get('file_path')}")
        print(f"    Content: {repr(file_data.get('content'))}")
        assert file_data.get("error") is False
        assert "Hello World!" in file_data.get("content", "")

    print("\n" + "=" * 60)
    print("  ALL PHASE 3 LANGCHAIN MCP CHECKS PASSED SUCCESSFULLY!")
    print("=" * 60)


@pytest.mark.asyncio
async def test_mcp_phase3():
    await run_phase3_langchain_verification()


if __name__ == "__main__":
    asyncio.run(run_phase3_langchain_verification())
